apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/alex-redmon/bitbucket-cloud-cli:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/alex-redmon/bitbucket-cloud-cli:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: bitbucket-cloud-cli
        chartPath: charts/bitbucket-cloud-cli
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/alex-redmon/bitbucket-cloud-cli"
          image.tag: "{{.DIGEST_HEX}}"
